### ISSUE TITLE
undefined constant CURLOPT_SAFE_UPLOAD

### ISSUE THREAD

**Issue by marcusysjgreen** [turnitin/moodle-mod_turnitintool#22]
When installing on Moodle 3.0 with PHP 5.4.45-0+deb7u2
I get a sequence of error messages along the following lines

Notice: Use of undefined constant CURLOPT_SAFE_UPLOAD - assumed 'CURLOPT_SAFE_UPLOAD' in /var/www/moodle/mod/turnitintool/comms.php on line 431

This happens when I click the Save and Display button during the creation of the assignment.

Can you advise

**Comment by davidmhatton** [comment]
Hi @marcusysjgreen 

The option `CURLOPT_SAFE_UPLOAD` was added into the `curl_setopt()` function in PHP version 5.5 (default value `FALSE`) and changed to have default value `TRUE` in PHP 5.6. Prior to that the curl upload system used the @ option and so php 5.4.45 probably won't recognise this parameter input.

My primary recommendation would be to upgrade your version of PHP.
If that is not an option for you, then as a workaround you could comment out _comms.php:429-431_.
Since the parameter doesn't exist in that version of PHP it makes little sense to try setting it. However there is a small chance that this could create some knock-on effects, so it's definitely a workaround of last resort.

Kind regards

David
